# shellcheck shell=bash
#
# The systemd service.
#
# The unit itself is generated by the agent's own CLI, and the agent rewrites it
# whenever it decides the file is out of date. Anything written into the unit by
# hand is therefore temporary. Drop-ins survive, so every adjustment below is a
# drop-in — not an edit.

service_apply() {
    _SERVICE_COUNT_BEFORE=$CHANGE_COUNT
    log_step "Service"

    if (( $(bot_count) == 0 )); then
        _service_configure_watchdog     # before install: it decides the unit's Type
        _service_install_unit
        _service_write_dropins
        _service_enable
        _service_verify
        return 0
    fi

    # Bots: one unit per bot, written here (not by the vendor's installer,
    # which knows only the default profile), pointing at the bot's profile.
    # The vendor's default unit, if it exists, is retired.
    require_root "installing the bot units"
    _service_retire_default
    local key
    while IFS= read -r key; do
        [[ -n $key ]] || continue
        bot_context "$key"
        _SERVICE_COUNT_BEFORE=$CHANGE_COUNT
        local SERVICE_NAME=$BOT_SERVICE
        _service_configure_watchdog
        _service_write_bot_unit
        _service_write_dropins
        _service_enable
        _service_verify
        bot_context_end
    done < <(bots)
}

# The default profile runs no gateway once bots exist: two processes on one
# data directory is what the preflight refuses, and the bots' profiles are
# where everything lives now.
_service_retire_default() {
    local default=${SERVICE_NAME}.service
    [[ $default == "$(bot_field "$(bots | head -n1)" SERVICE).service" ]] && return 0
    systemctl list-unit-files "$default" 2>/dev/null | grep -q "${default%%.*}" || return 0
    if systemctl is-enabled --quiet "$default" 2>/dev/null || systemctl is-active --quiet "$default" 2>/dev/null; then
        log_info "retiring the default-profile unit ${default}; the bots have their own"
        run systemctl disable --now "$default"
        run systemctl reset-failed "$default" || true
        mark_changed
    elif systemctl is-failed --quiet "$default" 2>/dev/null; then
        # Disabled, but still listed as failed from its last attempt to run:
        # that is what every "failed units" check shows first. Clear it.
        run systemctl reset-failed "$default"
        log_ok "cleared the failed state of the retired ${default}"
    else
        log_skip "${default} already retired"
    fi
}

# What a bot waits for at boot: the network, and the local services it talks
# to on its first turn — the bridge (its model) and the mail relay (its
# mailbox), when this installation runs them. Wants, not Requires: a bot on a
# hosted model has no use for the bridge, and a relay that is down must not
# take the Teams side with it. Ordering only; the units restart on their own.
_service_bot_deps() {             # -> the After=/Wants= lines of a bot unit
    local IFS=$' \t\n' deps=(network-online.target)
    is_true "${AGY_SHIM_ENABLED:-false}"  && deps+=("$(agyshim_unit_name).service")
    is_true "${MAILPROXY_ENABLED:-false}" && deps+=("$(mailproxy_unit_name).service")
    printf 'After=%s\nWants=%s\n' "${deps[*]}" "${deps[*]}"
}

# The bot's unit, modelled on the vendor's generated one (Type=notify with the
# watchdog, the same PATH and environment), pointed at the bot's profile.
_service_write_bot_unit() {
    local dir py home
    dir=$(hermes_install_dir); py="${dir}/venv/bin/python"
    home=$(getent passwd "$SERVICE_USER" | cut -d: -f6)
    local watchdog=${SERVICE_WATCHDOG_SECONDS:-0} type_line="Type=simple" watchdog_lines=""
    if [[ $watchdog != 0 ]]; then
        type_line="Type=notify"
        watchdog_lines=$'NotifyAccess=main\n'"WatchdogSec=${watchdog}s"
    fi
    if [[ $DRY_RUN == true ]]; then
        log_info "[dry-run] write $(service_unit_path) for ${BOT_DISPLAY_NAME} (profile ${BOT_HOME})"
        return 0
    fi
    write_file "$(service_unit_path)" 0644 <<EOF
# Managed by setup-hermes-agent: the ${BOT_DISPLAY_NAME} bot, profile ${BOT_KEY}.
[Unit]
Description=${BOT_DISPLAY_NAME} bot (agent gateway, profile ${BOT_KEY})
$(_service_bot_deps)
StartLimitIntervalSec=0

[Service]
${type_line}
${watchdog_lines}
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
ExecStart=${py} -m hermes_cli.main gateway run
WorkingDirectory=${BOT_HOME}
Environment="HOME=${home}"
Environment="USER=${SERVICE_USER}"
Environment="LOGNAME=${SERVICE_USER}"
Environment="PATH=${HERMES_HOME}/node:${dir}/venv/bin:${dir}/node_modules/.bin:${HERMES_HOME}/node/bin:${home}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Environment="VIRTUAL_ENV=${dir}/venv"
Environment="HERMES_HOME=${BOT_HOME}"
Environment="HERMES_SUPERVISED_CHILD=1"
Restart=always
RestartSec=5
RestartForceExitStatus=75
RestartPreventExitStatus=78
KillMode=mixed
KillSignal=SIGTERM
ExecReload=/bin/kill -USR1 \$MAINPID
ExecStopPost=-${py} -m gateway.cgroup_cleanup
TimeoutStopSec=70
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${BOT_SERVICE}

[Install]
WantedBy=multi-user.target
EOF
    run systemctl daemon-reload
}

service_unit_path() {
    printf '/etc/systemd/system/%s.service' "$SERVICE_NAME"
}

service_dropin_dir() {
    printf '/etc/systemd/system/%s.service.d' "$SERVICE_NAME"
}

# ---------------------------------------------------------------------------
# Watchdog
#
# Without this the generated unit is Type=simple, where systemd knows only that
# a process exists — not whether it is serving. Setting a watchdog interval
# makes the agent emit readiness and keep-alive notifications, so systemd can
# restart a wedged gateway rather than watching it sit there.
#
# Set before the unit is generated, because it is what selects Type=notify.
# ---------------------------------------------------------------------------
_service_configure_watchdog() {
    local seconds=${SERVICE_WATCHDOG_SECONDS:-0}
    if [[ $seconds == 0 ]]; then
        log_warn "no watchdog configured; the unit stays Type=simple and a wedged gateway will not be detected"
        return 0
    fi
    log_info "watchdog       ${seconds}s"
    # The CLI answers "not a recognized config key" here. It is wrong: the key
    # lands as gateway.systemd_watchdog_seconds in config.yaml, and that is
    # exactly what the gateway's own _systemd_watchdog_seconds() reads to decide
    # between Type=simple and Type=notify + WatchdogSec. The warning comes from
    # the setter's allowlist, not from the reader. Verified in hermes_cli/gateway.py.
    hermes_cli config set gateway.systemd_watchdog_seconds "$seconds" ||
        log_warn "could not set the watchdog interval; the unit may remain Type=simple"
}

# ---------------------------------------------------------------------------
# Unit installation, at the configured scope
#
# The CLI defaults to a *user* unit, which on a headless host means the service
# does not exist until someone logs in and does not survive logout without
# lingering. A system unit is what "runs at boot" actually requires.
# ---------------------------------------------------------------------------
_service_install_unit() {
    local -a args=(gateway install)

    if [[ $SERVICE_SCOPE == system ]]; then
        require_root "installing a system-scope unit"
        args+=(--system)
        [[ -n $SERVICE_USER ]] && args+=(--run-as-user "$SERVICE_USER")
    fi

    # Do not call the installer when the unit is already there. It answers
    # "Service already installed … Use --force" and installs nothing — but it
    # still starts the service and leaves root-owned files under the agent's
    # home, which the reclaim step then hands back and counts as a change. That
    # single call is what kept restarting a converged gateway on every run.
    # Drop-ins are ours and are converged separately; the vendor's unit only
    # needs (re)installing when it is missing.
    if [[ $DRY_RUN != true && -f $(service_unit_path) && $HERMES_INSTALLER_RAN != true ]]; then
        log_skip "unit exists at $(service_unit_path); not reinstalling"
        return 0
    fi
    [[ $HERMES_INSTALLER_RAN == true ]] && log_info "agent code changed this run; letting the vendor refresh its unit"

    # A system unit is installed by root; a user unit by the account that owns
    # it. Sending the system case through the service account is what produced
    # "System gateway install requires root. Re-run with sudo." from a run that
    # was already root.
    # The CLI answers "Service already installed … Use --force" on a re-run and
    # writes nothing. Marking that as a change restarted the gateway on every
    # run. Judge by the unit file itself: changed content, or a file that was
    # not there before, is a change; the same bytes are not.
    local unit_path before_hash after_hash
    unit_path=$(service_unit_path)
    before_hash=$( [[ -f $unit_path ]] && sha256sum "$unit_path" | cut -d' ' -f1 || printf absent )

    if [[ $SERVICE_SCOPE == system ]]; then
        hermes_cli_root "${args[@]}" || die "the agent CLI could not install the service unit"
    else
        hermes_cli "${args[@]}" || die "the agent CLI could not install the service unit"
    fi

    if [[ $DRY_RUN != true ]]; then
        after_hash=$( [[ -f $unit_path ]] && sha256sum "$unit_path" | cut -d' ' -f1 || printf absent )
        [[ $before_hash == "$after_hash" ]] || mark_changed
    fi
}

# ---------------------------------------------------------------------------
# Drop-ins
# ---------------------------------------------------------------------------
_service_write_dropins() {
    require_root "writing service drop-ins"
    ensure_dir "$(service_dropin_dir)" 0755

    # Here-string, not a pipe: a pipeline runs write_file in a subshell, where
    # the change flag it sets is discarded and the service is never restarted.
    local content
    content=$(_service_dropin_content)
    write_file "$(service_dropin_dir)/10-provisioner.conf" 0644 <<<"$content"

    run systemctl daemon-reload
}

_service_dropin_content() {
    cat <<EOF
# Managed by setup-hermes-agent. The agent regenerates its own unit file, so
# every adjustment lives here instead of in the unit itself.

[Unit]
# The generated unit disables start rate limiting entirely, so a gateway that
# cannot start retries every few seconds forever. Bound it: after ${SERVICE_START_LIMIT_BURST}
# failures in ${SERVICE_START_LIMIT_INTERVAL}s the unit stops and stays stopped, which is visible
# instead of merely noisy. Clear with: systemctl reset-failed ${SERVICE_NAME}
StartLimitIntervalSec=${SERVICE_START_LIMIT_INTERVAL}
StartLimitBurst=${SERVICE_START_LIMIT_BURST}
$(_service_onfailure_stanza)
[Service]
# A cold boot starts every gateway at once, each importing its venv and
# spawning its MCP servers; the default 90 s start timeout would kill a
# healthy gateway that is merely slow, and the retry pays the same price.
TimeoutStartSec=${SERVICE_START_TIMEOUT}
$(_service_privilege_stanza)$(_service_docker_stanza)
EOF
}

_service_onfailure_stanza() {
    [[ -n ${SERVICE_ON_FAILURE_UNIT:-} ]] || return 0
    printf 'OnFailure=%s\n' "$SERVICE_ON_FAILURE_UNIT"
}

# NoNewPrivileges stops the service tree from gaining privileges through setuid
# binaries, which is the sudo path. It says nothing about the container socket:
# if the service account can reach that, it can still arrange root on this host.
# Worth having, not worth mistaking for containment.
_service_privilege_stanza() {
    is_true "${SERVICE_HARDEN_NO_NEW_PRIVS:-true}" || return 0
    cat <<'EOF'
# Blocks escalation via setuid binaries (sudo) from inside the service tree.
# Does not restrict container-socket access — see README, Security posture.
NoNewPrivileges=true
EOF
}

# Declarative group membership beats usermod: it is visible in the unit, it is
# removed when the drop-in is removed, and it avoids the usual confusion where a
# freshly added group does not apply to an already-running process.
_service_docker_stanza() {
    [[ $TERMINAL_BACKEND == docker ]] || return 0
    getent group docker >/dev/null 2>&1 || return 0
    cat <<'EOF'
# Sandbox access, granted declaratively rather than by editing the account.
SupplementaryGroups=docker
EOF
}

# ---------------------------------------------------------------------------
# Enable and verify
# ---------------------------------------------------------------------------
# Restart only if THIS module changed the unit or a drop-in. The channels
# module restarts the gateway later when configuration changed; between the
# two, a converged run leaves the process alone.
_service_enable() {
    [[ $SERVICE_SCOPE == system ]] || { log_debug "user scope: the CLI manages enablement"; return 0; }
    converge_unit "${SERVICE_NAME}.service" "${_SERVICE_COUNT_BEFORE:-0}"
}

_service_verify() {
    [[ $DRY_RUN == true ]] && { log_info "[dry-run] would verify the service"; return 0; }
    [[ $SERVICE_SCOPE == system ]] || return 0

    # Give it a moment to fail, if it is going to.
    local waited=0
    while (( waited < 30 )); do
        if systemctl is-active --quiet "${SERVICE_NAME}.service"; then
            log_ok "${SERVICE_NAME} is active"
            _service_report_type
            return 0
        fi
        if systemctl is-failed --quiet "${SERVICE_NAME}.service"; then
            break
        fi
        sleep 2
        waited=$(( waited + 2 ))
    done

    log_error "${SERVICE_NAME} did not become active; last 30 journal lines:"
    journalctl -u "${SERVICE_NAME}.service" -n 30 --no-pager >&2 || true
    die "the service failed to start"
}

_service_report_type() {
    local type
    type=$(systemctl show -p Type --value "${SERVICE_NAME}.service" 2>/dev/null || printf '?')
    log_info "unit type      ${type}"
    [[ $type == notify ]] ||
        log_warn "unit is Type=${type}: systemd cannot distinguish 'running' from 'wedged'"
}
